### PR TITLE
Libre testnet node page was broken

### LINKED ISSUE #868: Libre-testnet nodes page is broken
After a couple of seconds the page stop working

imagen

### PR DESCRIPTION
**Pull request by Torresmorah**
### What does this PR do?

- Resolve #868 
- Change validation of features, because the previous one is true for strings

### Steps to test

1. check the change

### CODE REVIEW

**Review by fvives99 — APPROVED** [review]
LGTM

**Review by AngeloCG97 — APPROVED** [review]
LGTM

File: webapp/src/components/InformationCard/Information.js [hunk 1]
```diff
@@ -21,7 +21,7 @@ const Information = ({ info, classes, type, t }) => {
             <Typography variant="body1">{`${t('features')}:`}</Typography>
           </Box>
           <Box className="listBox">
-            {!!info?.features?.length ? (
+            {Array.isArray(info?.features) && info.features.length > 0  ? (
```
Comment (xavier506) [inline webapp/src/components/InformationCard/Information.js:24]: `{Array.isArray(info?.features) && info.features.length ?`
