### PR TITLE
fix: error on sign transaction

### LINKED ISSUE #228: Expected object run error
Set Env Vars that include default action for writer run

image

### PR DESCRIPTION
**Pull request by adriexnet**
### What does this PR do?

- Resolve #228 

### Steps to test

1. make run lacchain 
2. login with an entity account 
3. navigate to http://localhost:3000/lacchain/management
4. execute some transaction

#### CheckList

- [x] Follow proper Markdown format
- [x] The content is adequate
- [x] The content is available in both english and spanish
- [x] I Ran a spell check

### CODE REVIEW

**Review by xavier506 — APPROVED** [review]

File: scripts/build.sh [hunk 1]
```diff
@@ -24,6 +24,7 @@ if [ "$1" == "production" ]; then
        --build-arg react_app_eos_api_network_name="${REACT_APP_EOS_API_NETWORK_NAME}" \
        --build-arg react_app_eos_api_network_label="${REACT_APP_EOS_API_NETWORK_LABEL}" \
        --build-arg react_app_eos_api_network_logo="${REACT_APP_EOS_API_NETWORK_LOGO}" \
+       --build-arg react_app_eos_include_transaction="${REACT_APP_EOS_INCLUDE_TRANSACTION}" \
```
Comment (xavier506) [inline scripts/build.sh:27]: 👍

**Review by xavier506 — APPROVED** [review]
