### PR TITLE
Feat/update prices logic & fix hasura migrations

### LINKED ISSUE #386: Telos Price API
We need to bring in the TLSO price for blow rewards calculations

### PR DESCRIPTION
**Pull request by JustinCast**
### What does this PR do?
- Resolve #386 

### Steps to test

1. make start

#### CheckList

- [ ] Follow proper Markdown format
- [ ] The content is adequate
- [ ] The content is available in both english and spanish
- [ ] I Ran a spell check

### CODE REVIEW

**Comment by xavier506** [comment]
@JustinCast  please check conflicts

File: hasura/migrations/1606135484776_create_table_public_setting/up.sql [hunk 1]
```diff
@@ -1 +1 @@
-CREATE TABLE "public"."setting"("id" serial NOT NULL, "eos_price" numeric NOT NULL, PRIMARY KEY ("id") );
+CREATE TABLE "public"."setting"("id" serial NOT NULL, "token_price" numeric NOT NULL, PRIMARY KEY ("id") );
```
Comment (adriexnet) [inline hasura/migrations/1606135484776_create_table_public_setting/up.sql:1]: @JustinCast any migration should be edited because hasura track each migration to know witch one is already executed so this migration will works if you setup a new environment from the scratch but will ve ignored for other that already executed it with the original version like lacchain, jungle and mainnet

File: .env.telostestnet [hunk 2]
```diff
@@ -68,4 +69,5 @@ REACT_APP_EOS_CHAIN_ID=1eaa0824707c8c16bd25145493bf062aecddfeb56c736f6ba6397f319
 REACT_APP_EOS_USE_BP_JSON_ON_CHAIN=false
 REACT_APP_EOS_BP_JSON_ON_CHAIN_CONTRACT=producerjson
 REACT_APP_EOS_BP_JSON_ON_CHAIN_TABLE=producerjson
-REACT_APP_EOS_BP_JSON_ON_CHAIN_SCOPE=producerjson
\ No newline at end of file
+REACT_APP_EOS_BP_JSON_ON_CHAIN_SCOPE=producerjson
+REACT_APP_TOKEN_SYMBOL=TLOS
```
Comment (adriexnet) [inline .env.telostestnet:73]: @JustinCast I think that this new environment variable should be added to kubernetes configmap and push files

Comment (adriexnet) [reply .env.telostestnet:73]: also it should be in the dockerfile

File: hasura/migrations/1606135484776_create_table_public_setting/up.sql (hunk 1 above)
Comment (adriexnet) [reply hasura/migrations/1606135484776_create_table_public_setting/up.sql:1]: this should be a new migration to alter the previous table and rename the column

**Review by adriexnet — CHANGES_REQUESTED** [review]

File: .env.telostestnet (hunk 2 above)
Comment (JustinCast) [reply .env.telostestnet:72]: @adriexnet thanks for the observations. Fixed!

**Comment by JustinCast** [comment]
@xavier506 @adriexnet please take a look at the latest changes!

File: .env.telostestnet [hunk 3]
```diff
@@ -66,4 +68,5 @@ REACT_APP_EOS_CHAIN_ID=1eaa0824707c8c16bd25145493bf062aecddfeb56c736f6ba6397f319
...
```
Comment (xavier506) [inline .env.telostestnet:72]: did you add the equivalent token symbol `=EOS` for the other environments?

**Comment by JustinCast** [comment]
@adriexnet @xavier506
